version: "2"
checks:
  method-count:
    config:
      threshold: 25
plugins:
  duplication:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-7"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
