name: Mutation Testing Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Run Stryker (and report results)
      run: npx stryker run --reporters json,dashboard
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
